version: 0.2

env:
  variables:
    TF_VERSION: "0.11.8"

phases:

  install:
    commands:
      # install required binary
      - "curl -s -qL -o /usr/bin/jq https://stedolan.github.io/jq/download/linux64/jq"
      - "chmod +x /usr/bin/jq"
      - "cd /usr/bin"
      - "curl -s -qL -o terraform.zip https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip"
      - "unzip -o terraform.zip"

  build:
    commands:
      - cd "$CODEBUILD_SRC_DIR"
      - cd "environments/$TF_ENV/"
      - terraform init -no-color
      - terraform $TF_ACTION -no-color

  post_build:
    commands:
      - echo "terraform $TF_ACTION completed on `date`"

artifacts:
  files:
    - '**/*'
